version: '3.8'

services:
  elixir-codespaces-example:
    build: .
    init: true
    privileged: true
    command: sleep infinity
    volumes:
      - ..:/home/vscode/workspace:cached
  postgres:
    image: postgres:15.6-alpine3.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
